### ISSUE TITLE
"Rate the app" dialog appears too often

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-android#12]
Once accepted or dismissed once, it should never appear again.

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-android/blob/master/app/src/main/java/org/supla/android/RateApp.java#L68

https://github.com/SUPLA/supla-android/blob/master/app/src/main/java/org/supla/android/RateApp.java#L78

https://github.com/SUPLA/supla-android/blob/master/app/src/main/java/org/supla/android/RateApp.java#L88

**Comment by fracz** [comment]
Ok. 100 years seems to be quite enough to ask for a new assessment :-D

I must have been dismissing the dialog by clicking the backdrob and, therfore, falling into the "neutral" decision.
