### ISSUE TITLE
Energy meter. Enable historical measurement data caching

### ISSUE THREAD

**Issue by D0m3L** [SUPLA/supla-android#198]
Hi!

I've been using Supla for 7 months now. Great stuff! Big kudos guys!

There is one thing I noticed in Andorid app which is annoying and worsens over time: retrieving historical measurement data for use in the graph section. Each time I look on the graph section there is newly created task of "Retrieving data from the server" - the problem is that the application each time "ask" the supla-cloud server for data since "_the beginning of the world_". This is not effective as historical data by default does not suppose to change over time. 

In my case, each time I enter graph section, there are 35 API request for channel measurement-logs: starting with `afterTimestamp=1` parameter and ending on something close to current timestamp. Briefly, at them moment, there is ~30x330kB (~10MB) data downloaded from the API each time (7 mothns of MEW-01 usage). 
At my current setup complete data acquisition takes around 30s and is increasing each month as the amount of data to be downloaded increases as well.

Would it be possible to cache initially retrieved historical measurement data (which, in principle, should not change over time) within the app, thus access to the graph section would be significantly shortened?

Thanks in advance.
D0m3L

**Comment by przemyslawzygmunt** [comment]
The application should store data in a local database. It should only get the missing data. There may be a write problem.

**Comment by D0m3L** [comment]
@przemyslawzygmunt thats interesting. Shouldn't the app ask for the Storage permission after installation? In my case the only permission I can play with is the "Location" one, but with enabled or disabled no difference. 
In my scenerio it seems to be broken. I've checked that on 2 devices and the problem is the same - everything is smooth (changing graphs, 7-30-90 days periods etc., getting newly available data) but only within "one device session". When I close the app and run it again, the app is requesting data from the scratch after I access the device from app. By some reason the previous "session" data was not persist. 

There seems to be some data stored in app as shown below, but the User data not the Cache does not increase a lot:

![image](https://user-images.githubusercontent.com/23291471/94374545-52c86700-010d-11eb-9389-a7eb11df7a3b.png)

Do you have any suggestions?

**Comment by przemyslawzygmunt** [comment]
Change this line
https://github.com/SUPLA/supla-android/blob/master/app/src/main/java/org/supla/android/Trace.java#L13

to private static final int  LOGGING_LEVEL = ERRORS_WARNINGS_INFO_DEBUG;

Then check the logs.
Database file location:
//data/data/org.supla.android/databases/supla_measurements.db

**Comment by D0m3L** [comment]
Whooh. 

I finally managed to fix that, now the app and measurement history works as intended.
 
The problem was on my data quality side. There was a one record missing in the `supla_em_log` table from the very begging of MEW-01 operation.
API response for `/api/2.2.0/channels/3/measurement-logs?order=ASC&limit=2&offset=0` was
```JSON
[
  {		
    "date_timestamp": "1581709200",
    "phase1_fae": null,
    "phase1_rae": null,
    "phase1_fre": null,
    "phase1_rre": null,
    "phase2_fae": null,
    "phase2_rae": null,
    "phase2_fre": null,
    "phase2_rre": null,
    "phase3_fae": null,
    "phase3_rae": null,
    "phase3_fre": null,
    "phase3_rre": null,
    "fae_balanced": null,
    "rae_balanced": null
  },
  {
    "date_timestamp": "1581710400",
    "phase1_fae": "540",
    "phase1_rae": "88",
    "phase1_fre": "56",
    "phase1_rre": "8",
    "phase2_fae": null,
    "phase2_rae": null,
    "phase2_fre": null,
    "phase2_rre": null,
    "phase3_fae": null,
    "phase3_rae": null,
    "phase3_fre": null,
    "phase3_rre": null,
    "fae_balanced": null,
    "rae_balanced": null
  }
]
```
while the `min` value in app expected value = `1581709800`.

Anyway, when I manually inserted missing `2020-02-14 19:50:00` (`1581709800`) record with "2" values, the problem was solved. 

@przemyslawzygmunt thank you for your support. I will close this issue as the functionality I requested is already implemented and works fine and the problem seems to be on my end.
Cheers.

**Comment by przemyslawzygmunt** [comment]
Thanks for the investigation. I will try to modify the server so that it does not write data if they are all nulls.
