### ISSUE TITLE
A bug that allowed showing the channel in a detailed view

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-android#217]
![image](https://user-images.githubusercontent.com/6603397/105699511-c2a5fd00-5f07-11eb-835c-42f90d7d38ca.png)

**Comment by klew** [comment]
I reproduced this problem. I was on RGB view and I tried to save current color to bookmark, when I accidentally dragged location bar. I tried it again and I managed to drag channel (as in previous comment) and location bar. To reproduce it you have to hold finger at non-reactive part of the screen in detailed view. 
![image](https://user-images.githubusercontent.com/205610/105917722-0c3f3680-6033-11eb-8e6c-cc1308ad1b51.png)
