### ISSUE TITLE
SSID matcher for add device wizard should be more flexible

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#306]
Please change SSID matcher for "add device wizard", so it will match from 4 to 12 of hex digits at the end of SSID name.

https://github.com/SUPLA/supla-android/blob/0ef2bbc75bdabe34cff4c5c4502a435c0e026bbc/app/src/main/java/org/supla/android/AddDeviceWizardActivity.java#L845

**Comment by przemyslawzygmunt** [comment]
Duplicate
https://github.com/SUPLA/supla-android/issues/305
