### ISSUE TITLE
Problem z uruchamianiem scen

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#382]
Starting/stopping scene from app doesn't work with log: Failed to start scene xx.

**Comment by Basmart** [comment]
How do you run scene from app on smartphone?

**Comment by przemyslawzygmunt** [comment]
Scenes can be run from the prototype version.
https://github.com/SUPLA/supla-android/pull/377

**Comment by Basmart** [comment]
Gents, za wysokie progi jak dla mnie. Nie jestem programistą :-(
chyba, że nauczycie mnie jak się kompilute ten kod do apk.
Mam sporo czasu, na testy :-)

**Comment by przemyslawzygmunt** [comment]
Sugeruję zaczekać na oficjalne wydanie.

**Comment by Basmart** [comment]
OK.
