### ISSUE TITLE
When new scene is added in cloud, list of scenes in app is not refreshed

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#395]
To reproduce:
1. Open app on "scenes" view
2. In cloud create new scene
3. App reconnects, however new scene is not visible
4. Switch to channels/groups and go back to scenes -> new scene is visible

The same problem is visible when scene icon is changed - it doesn't refresh the list

**Comment by mipolansk** [comment]
The same issue was with removing. Also should be already fixed.
