### ISSUE TITLE
Solve problem with keeping charts configuration for EMs with and without "vector balance" data

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#423]
Some EMs have ability to show "vector balance" energy consumption/production (i.e. MEW-01) and some doesn't have such option (i.e. all single-phase devices).

Currently Supla App remembers chart settings for each function. So if we set "vector balance - month" view on MEW-01's chart it is saved and when we enter it again, then the same chart view will be automatically opened.

However it causes some problems with EMs without "vector balance" function. For such EMs there is no such option on charts.

Following solution is proposed:
1. Chart state for EM with vector balance should be preserved when we enter another EM and we don't change chart format.
2. Chart state for EM wihtout vector balance should be set to standard "arithmetic balance" with the same time granulation like for "vector balance" set on another EM.

**Comment by mipolansk** [comment]
Released in 24.10
