### ISSUE TITLE
"Delete" account button doesn't work and "black arrow" problem

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#433]
When I go to edit account and click "delete", then click "cancel", "delete" button stops working (it doesn't react).

There is also small "black arrow" problem. To reproduce it, try to login to missing account (no access, etc). Then yellow screen with login issue appears. Click "Accounts", then click on pencil icon to edit account and there will be incorrect "go back" icon set on top green bar:
![image](https://user-images.githubusercontent.com/205610/229739216-e97655f3-8a5a-4c37-bb74-aa2a2b42b263.png)

**Comment by mipolansk** [comment]
Looks like the problem is already fixed.
