### ISSUE TITLE
Change behavior of Roller Shutter button on channel list view

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#452]
Version 23.05 added buttons "open" and "close" for roller shutter on a channel list view. However there is no option to "stop" it during the movement.
IO devices with recent SW version do support exteneded set of actions for roller shutter channel, which includes "move down or stop" and "move up or stop".
Those roller shutter buttons should use those actions instead of standard "close" "open" when IO device supports it.
This capability is stored in channel's Flags parameter: SUPLA_CHANNEL_FLAG_RS_SBS_AND_STOP_ACTIONS 0x0080 

Caption of button should remain the same, so it should be "close" and "open" regardless of executed action.

**Comment by mipolansk** [comment]
Released in 23.07.01
