### ISSUE TITLE
Problems related to keeping detail view opened after reconnect with server or app hide and open

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#482]
On version 23.07 detail view remain open after reconnect with server and after app hide and open.

There are some problems with this functionality:
1. Channel may be removed/hidden on Cloud. Current behavior: detail view is open on non-existing channel. Expected: go back to channel list
2. Channel function may change on Cloud. Current behavior: detail view is open and depending on new function some buttons work or not, timer is also visible with invalid state "offline". Expected: probably it should go back to channel list
3. Channel name may change on Cloud. Current behavior: name is not updated in detail view. Expected: name should be updated

**Comment by mipolansk** [comment]
Released in 23.07.02
