### ISSUE TITLE
Endless "loader" after deleting user account

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-android#503]
App version: 23.09-BETA2

Steps to reproduce:
1. Create few profiles in app
2. Try to delete one profile with option "forget only on this device"
3. App stays on endless loader:

![image](https://github.com/SUPLA/supla-android/assets/205610/a71eb121-4b36-4d4a-b324-4aa9452aa879)

**Comment by mipolansk** [comment]
Works correct in 24.02
